version: 0.2

phases:
  install:
     runtime-versions:
      nodejs: 18
  pre_build:  
    commands:
      - echo "Cleaning up node_modules and package-lock.json"
      - rm -rf node_modules package-lock.json
      - npm cache clean --force
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Building the project"
      - npm run build
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist # Replace with your build directory (e.g., dist, build)