import React from "react";
import { languageActionType, Permissions } from "../constants";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { _ } from "lodash";

import {
    faPieChart,
    faUser,
    faTruck,
    faUserGroup,
    faHome,
    faBoxes,
    faPrint,
    faBookmark,
    faBoxOpen,
    faMoneyCheckDollar,
    faGauge,
    faMoneyBills,
    faQuoteRight,
    faDollarSign,
    faReceipt,
    faArrowRight,
    faArrowLeft,
    faArrowsLeftRight,
    faMoneyBill,
    faEnvelope,
    faCartShopping,
    faChartColumn,
    faGear,
    faMapLocation,
    faBasketShopping,
    faSms,
    faCube,
    faFile,
    faBox,
    faRulerHorizontal,
    faLanguage,
    faShieldHalved,
    faLayerGroup,
    faLocationCrosshairs,
    faGifts,
    faCashRegister,
} from "@fortawesome/free-solid-svg-icons";
import { getFormattedMessage } from "../shared/sharedMethod";

export default [
    {
        title: "dashboard.title",
        name: "dashboard",
        fontIcon: <FontAwesomeIcon icon={faPieChart} />,
        to: "/app/dashboard",
        class: "d-flex",
        permission: Permissions.MANAGE_DASHBOARD,
        items: [
            {
                title: getFormattedMessage("dashboard.title"),
                to: "/app/dashboard",
            },
        ],
    },
    {
        title: "allusers.title",
        name: "All Users",
        fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
        class: "d-flex",
        is_submenu: "true",
        permission:
            Permissions.MANAGE_CUSTOMERS || Permissions.MANAGE_ADMIN || Permissions.MANAGE_SALESMAN ||  Permissions.MANAGE_WAREHOUSES || Permissions.MANAGE_DISTRIBUTORS || Permissions.MANAGE_SUPERVISOR,
           subPath: {
                customerSubPath: "/app/customers",
                userSubPath: "/app/users",
                distributorSubPath: "/app/distributor",
                warehouseSubPath: "/app/warehouse",
                supervisorSubPath: "/app/supervisor",
                salManSubPath: "/app/salesman",
                chanelSubPath: "/app/chanels",
            },
            subMenu: [
            {
                title: "admin.title",
                name: "admins",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/app/users",
                class: "d-flex",
                permission: Permissions.MANAGE_ADMIN,
            },
            {
                title: "distributor.title",
                name: "Distributor",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/app/distributor",
                class: "d-flex",
                permission: Permissions.MANAGE_DISTRIBUTORS,
            },
            {
                title: "allwarehouse.title",
                name: "All warehouses",
                fontIcon: <FontAwesomeIcon icon={faHome} />,
                to: "/app/warehouse",
                class: "d-flex",
                permission: Permissions.MANAGE_WAREHOUSES,

            },
            {
                title: "allsupervisor.title",
                name: "All Supervisor",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/app/supervisor",
                class: "d-flex",
                permission: Permissions.MANAGE_SUPERVISOR,

            },
            {
                title: "sman.title",
                name: "sman.title",
                fontIcon: <FontAwesomeIcon icon={faUser} />,
                to: "/app/salesman",
                class: "d-flex",
                permission: Permissions.MANAGE_SALESMAN,
            },
            {
                title: "alloutlets.title",
                name: "All Outlets",
                fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
                to: "/app/customers",
                class: "d-flex",
                permission: Permissions.MANAGE_CUSTOMERS,
            },
            {
                title: "Chanels",
                name: "chanels",
                fontIcon: <FontAwesomeIcon icon={faTruck} />,
                to: "/app/chanels",
                class: "d-flex",
                permission: Permissions.MANAGE_CHANNEL,
            },
        ],
    },
    {
        title: "products.title",
        name: "products",
        fontIcon: <FontAwesomeIcon icon={faBoxes} />,
        to: "/app/products",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_PRODUCTS,
        subPath: {
            productsSubPath: "/app/products",
            categoriesSubPath: "/app/product-categories",
            variationsSubPath: "/app/variations",
            brandsSubPath: "/app/brands",
            unitsSubPath: "/app/units",
            baseUnitsSubPath: "/app/base-units",
            barcodeSubPath: "/app/print/barcode",
            productInventorySubPath: "/app/inventory",
        },
        subMenu: [
            {
                title: "Products List",
                to: "/app/products",
                name: "products",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faBoxes} />,
                permission: Permissions.MANAGE_PRODUCTS,
            },
            {
                title: "product.categories.title",
                name: "product categories",
                fontIcon: <FontAwesomeIcon icon={faBoxOpen} />,
                to: "/app/product-categories",
                class: "d-flex",
                permission: Permissions.MANAGE_PRODUCT_CATEGORIES,
            },


            {
                title: "brands.title",
                name: "brands",
                fontIcon: <FontAwesomeIcon icon={faBookmark} />,
                to: "/app/brands",
                path: "/app/create-brand",
                class: "d-flex",
                permission: Permissions.MANAGE_BRANDS,
            },

            {
                title: "base-units.title",
                name: "base units",
                fontIcon: <FontAwesomeIcon icon={faRulerHorizontal} />,
                to: "/app/base-units",
                class: "d-flex",
                permission: Permissions.MANAGE_UNITS,
            },

            {
                title: "Product Inventory",
                name: "Product Inventory",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                to: "/app/inventory",
                class: "d-flex",
                permission: Permissions.MANAGE_INVENTORY,
            },

        ],
    },
    {
        title: "Gifts",
        name: "Gifts",
        fontIcon: <FontAwesomeIcon icon={faReceipt} />,
        to: "/app/gift",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_GIFTS ||Permissions.MANAGE_GIFT_HISTORY || Permissions.MANAGE_GIFT_INVENTORY,
        subPath: {
            purchaseReturnSubPath: "/app/gifts",
            purchasesSubPath: "/app/gift-history",
        },
        subMenu: [
            {
                title: "gifts.title",
                name: "Gift List",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                to: "/app/gifts",
                class: "d-flex",
                permission: Permissions.MANAGE_GIFTS,
            },
            {
                title: "gifts.submitiion.title",
                name: "Gifts Submitted History",
                fontIcon: <FontAwesomeIcon icon={faReceipt} />,
                to: "/app/gift-history",
                class: "d-flex",
                permission: Permissions.MANAGE_GIFT_HISTORY,
            },
            {
                title: "Gift Inventory",
                name: "Gift Inventory",
                fontIcon: <FontAwesomeIcon icon={faBox} />,
                to: "/app/gift-inventory",
                class: "d-flex",
                permission: Permissions.MANAGE_GIFT_INVENTORY,
            },
        ],
    },
    {
        title: "Pos",
        name: "pos",
        fontIcon: <FontAwesomeIcon icon={faBoxes} />,
        class: "d-flex",
        is_submenu: "true",
        permission:Permissions.MANAGE_ASSIGNED_CUSTOMER || Permissions.MANAGE_STOCKIN_PRODUCT || Permissions.MANAGE_STOCKOUT_PRODUCT || Permissions.MANAGE_STOCKIN_GIFT || Permissions.MANAGE_TRACK_SALESMAN,
        subPath: {
            assignCustomerSubPath: "/app/assign-customer",
            assignCustomerListSubPath: "/app/assign-customer-list",
            loadStockSubPath: "/app/load",
            stockInSubPath: "/app/assign-product-list",
            stockOutSubPath: "/app/stockout-product-list",
            stockInGiftSubPath: "/app/assigned-gift-list",
            salemantrackerSubPath: "/app/track-all-salesman",
            // stockOutSubPath: "/app/stockout",

        },
        subMenu: [
            {
                title: "Assigned Customer",
                to: "/app/assign-customer-list",
                name: "Assingned Customer",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
                permission:Permissions.MANAGE_ASSIGNED_CUSTOMER,
                items: [
                    {
                        title:"Assign Customer List",
                        to: "/app/assign-customer-list",
                    },
                ],
            },

            {
                title: "Load Product",
                name: "Load Product",
                fontIcon: <FontAwesomeIcon icon={faBox} />,
                to: "/app/assign-product-list",
                class: "d-flex",
                permission:Permissions.MANAGE_STOCKIN_PRODUCT,
                items: [
                    {
                        title:"Load Product",
                        to: "/app/assign-product-list",
                    },
                ],
            },
            {
                title: "StockOut Product",
                name: "Unload Product",
                fontIcon: <FontAwesomeIcon icon={faBox} />,
                to: "/app/stockout-product-list",
                class: "d-flex",
                permission:Permissions.MANAGE_STOCKOUT_PRODUCT,
                items: [
                    {
                        title:"Unload Product",
                        to: "/app/stockout-product-list",
                    },
                ],
            },
            {
                title: "Load Gift",
                name: "Load Gift",
                fontIcon: <FontAwesomeIcon icon={faBox} />,
                to: "/app/assigned-gift-list",
                class: "d-flex",
                permission:Permissions.MANAGE_STOCKIN_GIFT,
                items: [
                    {
                        title:"Assigned Gift List",
                        to: "/app/assigned-gift-list",
                    },
                ],
            },
            {
                title: "Salesman Tracker",
                to: "/app/track-all-salesman",
                name: "Salesman Tracker",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                permission:Permissions.MANAGE_TRACK_SALESMAN,
            },
        ]
    },

    {
        title: "Sales & Returns",
        name: "Sales & Returns",
        fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_SALE,
        subPath: {
            salesSubPath: "/app/all-sales",
            salesReturnSubPath: "/app/sale-return",
        },
        subMenu: [
            {
                title: "sales.title",
                name: "sales.title",
                fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
                class: "d-flex",
                to: "/app/all-sales",
                permission: Permissions.MANAGE_SALE,
                items: [
                    {
                        title:"sales",
                        to: "/app/all-sales",
                    },
                ],
            },
            {
                title: "sales-return.title",
                name: "sales return",
                fontIcon: <FontAwesomeIcon icon={faArrowRight} />,
                to: "/app/sale-return",
                class: "d-flex",
                permission: Permissions.MANAGE_SALE_RETURN,
                items: [
                    {
                        title:"sales return",
                        to: "/app/sale-return",
                    },
                ],
            },
        ],
    },

    {
        title: "cash.title",
        name: "Cash",
        fontIcon: <FontAwesomeIcon icon={faMoneyBills} />,
        to: "/app/gift",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_CASH,
        subPath: {
            purchaseReturnSubPath: "/app/all-cash-list",
        },
        subMenu: [
            {
                title: "cash.all.title",
                name: "Cash List",
                fontIcon: <FontAwesomeIcon icon={faMoneyBill} />,
                to: "/app/all-cash-list",
                class: "d-flex",
                permission: Permissions.MANAGE_CASH,
            },
        ],
    },
    {
        title: "mileage.record.title",
        name: "Mileage Record",
        fontIcon: <FontAwesomeIcon icon={faGauge} />,
        to: "/app/gift",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_MILEAGE,
        subPath: {
            purchaseReturnSubPath: "/app/mileage-records",
        },
        subMenu: [
            {
                title: "mileage.record.history.title",
                name: "Mileage history",
                fontIcon: <FontAwesomeIcon icon={faGauge} />,
                to: "/app/mileage-records",
                class: "d-flex",
                permission: Permissions.MANAGE_MILEAGE,
            },

        ],
    },
    {
        title: "location.title",
        name: "Location",
        fontIcon: <FontAwesomeIcon icon={faLocationCrosshairs} />,
        class: "d-flex",
        is_submenu: "true",
        subPath: {
            countrySubPath: "/app/country",
            regionSubPath: "/app/region",
            areaSubPath: "/app/area",
            subAreaSubPath: "/app/sub-area"
        },
        permission:
            Permissions.MANAGE_LOCATION || Permissions.MANAGE_COUNTRY || Permissions.MANAGE_REGION || Permissions.MANAGE_AREA,
        subMenu: [
            {
                title: "Country",
                name: "Country",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/app/country",
                class: "d-flex",
                permission: Permissions.MANAGE_COUNTRY,
            },
            {
                title: "region.title",
                name: "Region",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/app/region",
                class: "d-flex",
                permission: Permissions.MANAGE_REGION,
            },
            {
                title: "area.title",
                name: "Area",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/app/area",
                class: "d-flex",
                permission: Permissions.MANAGE_AREA,
            },
            {
                title: "SubArea",
                name: "SubArea",
                fontIcon: <FontAwesomeIcon icon={faMapLocation} />,
                to: "/app/sub-area",
                class: "d-flex",
                permission: Permissions.MANAGE_SUB_AREA,
            },



        ],
    },
    {
        to: "/app/pos",
        class: "d-none",
        name: "pos",
        title: "header.pos.title",
        permission: Permissions.MANAGE_POS_SCREEN,
    },
    {
        title: "Coupons",
        name: "Coupons",
        fontIcon: <FontAwesomeIcon icon={faBox} />,
        to: "/app/coupons",
        class: "d-flex",
        permission:Permissions.MANAGE_COUPON,
        items: [
            {
                title:"Coupons",
                to: "/app/coupons",
            },
        ],
    },
    {
        title: "checkin.checkout.title",
        name: "CheckIn & Checkout",
        fontIcon: <FontAwesomeIcon icon={faArrowsLeftRight} />,
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_CHECKIN,
        subPath: {
            purchaseReturnSubPath: "/app/checkin",
            checkoutSubPath: "/app/checkout",
        },
        subMenu: [
            {
                title: "CheckIn History",
                name: "CheckIn History",
                fontIcon: <FontAwesomeIcon icon={faArrowRight} />,
                to: "/app/checkin",
                class: "d-flex",
                permission: Permissions.MANAGE_CHECKIN,
            },
            {
                title: "CheckOut History",
                name: "CheckOut History",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                to: "/app/checkout",
                class: "d-flex",
                permission: Permissions.MANAGE_CHECKOUT,
            },
        ],
    },
    {
        title: "credit.collection",
        name: "credit.collection",
        fontIcon: <FontAwesomeIcon icon={faBox} />,
        to: "/app/collections",
        class: "d-flex",
        permission:Permissions.MANAGE_CREDIT_COLLECTION,
        items: [
            {
                title:"Credit Collection",
                to: "/app/collections",
            },
        ],
    },

    {
        title: "survey.title",
        name: "Survey",
        fontIcon: <FontAwesomeIcon icon={faReceipt} />,
        to: "/app/survey",
        class: "d-flex",
        is_submenu: "true",
        permission: Permissions.MANAGE_SURVEY,
        subPath: {
            surveyQuestionSubPath: "/app/question",
            surveyReportSubPath: "/app/survey",
        },
        subMenu: [
            {
                title: "Survey Questions",
                name: "Survey questions",
                fontIcon: <FontAwesomeIcon icon={faReceipt} />,
                to: "/app/question",
                class: "d-flex",
                permission: Permissions.MANAGE_QUESTION,
            },
            {
                title: "Survey Reports",
                name: "Survey Reports",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                to: "/app/survey",
                class: "d-flex",
                permission: Permissions.MANAGE_SURVEY,
            },
        ],
    },
    {
        title: "reports.title",
        name: "reports",
        fontIcon: <FontAwesomeIcon icon={faBoxes} />,
        to: "/app/report/report-sale",
        class: "d-flex",
        is_submenu: "true",
        fontIcon: <FontAwesomeIcon icon={faChartColumn} />,
        to: "/app/report/report-warehouse",
        path: "/app/report/report-sale",
        stockPath: "/app/report/report-stock",
        salesReturnReportPath: "/app/report/report-return-sale",
        giftReportPath: "/app/report/report-gift",
        purchasePath: "/app/report/report-purchase",
        topSellingPath: "/app/report/report-top-selling-products",
        stockDetailPath: "/app/report/report-detail-stock",
        productQuantityAlertPath: "/app/report/report-product-quantity",
        supplierReportPath: "/app/report/suppliers",
        profitLossReportPath: "/app/report/profit-loss",
        supplierReportDetailsPath: "/app/report/suppliers/details",
        bestCustomerReportPath: "/app/report/best-customers",
        customerReportPath: "/app/report/customers",
        customerReportDetailsPath: "/app/report/customers/details",
        registerReportPath: "/app/report/register",
        cashAssignReportPath: "/app/report/report-cash-assign",
        mileageReportPath: "/app/report/report-mileage",
        productReportPath: "/app/report/report-products",
        productReportDetailsPath: "/app/report/report-detail-product",
        giftInventoryReportDetailsPath: "/app/report/report-inventory-gifts",
        class: "d-flex",
        isSamePrefix: false,
        permission: Permissions.MANAGE_REPORTS || Permissions.MANAGE_CASH_REPORTS || Permissions.MANAGE_GIFT_INVENTORY_REPORTS || Permissions.MANAGE_PRODUCT_REPORTS || Permissions.MANAGE_SALE_REPORTS || Permissions.MANAGE_SALE_RETURN_REPORTS || Permissions.MANAGE_GIFT_REPORTS || Permissions.MANAGE_INVENTORY_REPORTS || Permissions.MANAGE_STOCK_ALERT_REPORTS || Permissions.MANAGE_CUSTOMER_REPORTS,
        subMenu: [
            {
                title: "sale.reports.title",
                to: "/app/report/report-sale",
                name: "sale.reports.title",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faCartShopping} />,
                permission: Permissions.MANAGE_SALE_REPORTS,
            },
            {
                title: "sale.return.reports.title",
                to: "/app/report/report-return-sale",
                name: "sale.return.reports.title",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                permission: Permissions.MANAGE_SALE_RETURN_REPORTS,
            },
            {
                title: "gift.reports.title",
                to: "/app/report/report-gift",
                name: "gift.reports.title",
                class: "d-flex",
                fontIcon: <FontAwesomeIcon icon={faBoxes} />,
                permission: Permissions.MANAGE_GIFT_REPORTS,
            },
            {
                title: "customer.report.title",
                name: "customer.report.title",
                fontIcon: <FontAwesomeIcon icon={faUserGroup} />,
                to: "/app/report/customers",
                class: "d-flex",
                permission: Permissions.MANAGE_CUSTOMER_REPORTS,
            },
            {
                title: "product.report",
                name: "product.report",
                fontIcon: <FontAwesomeIcon icon={faPrint} />,
                to: "/app/report/report-products",
                class: "d-flex",
                permission: Permissions.MANAGE_PRODUCT_REPORTS,
            },
            {
                title: "stock.reports.title",
                name: "stock.reports.title",
                fontIcon: <FontAwesomeIcon icon={faBoxOpen} />,
                to: "/app/report/report-stock",
                class: "d-flex",
                permission: Permissions.MANAGE_INVENTORY_REPORTS,
            },
            {
                title: "gift.inventory.report",
                name: "gift.inventory.report",
                fontIcon: <FontAwesomeIcon icon={faGifts} />,
                to: "/app/report/report-inventory-gifts",
                class: "d-flex",
                permission: Permissions.MANAGE_GIFT_INVENTORY_REPORTS,
            },
            // {
            //     title: "top-selling-product.reports.title",
            //     name: "top-selling-product.reports.title",
            //     fontIcon: <FontAwesomeIcon icon={faBookmark} />,
            //     to: "/app/report/report-top-selling-products",
            //     class: "d-flex",
            //     permission: Permissions.MANAGE_DASHBOARD,
            // },
            {
                title: "product.quantity.alert.reports.title",
                name: "product.quantity.alert.reports.title",
                fontIcon: <FontAwesomeIcon icon={faRulerHorizontal} />,
                to: "/app/report/report-product-quantity",
                class: "d-flex",
                permission: Permissions.MANAGE_STOCK_ALERT_REPORTS,
            },

            // {
            //     title: "profit-loss.reports.title",
            //     name: "profit-loss.reports.title",
            //     fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
            //     to: "/app/report/profit-loss",
            //     class: "d-flex",
            //     permission: Permissions.MANAGE_DASHBOARD,
            // },
            // {
            //     title: "best-customer.report.title",
            //     name: "best-customer.report.title",
            //     fontIcon: <FontAwesomeIcon icon={faPrint} />,
            //     to: "/app/report/best-customers",
            //     class: "d-flex",
            //     permission: Permissions.MANAGE_DASHBOARD,
            // },

            {
                title: "cash.assign.report",
                name: "cash.assign.report",
                fontIcon: <FontAwesomeIcon icon={faCashRegister} />,
                to: "/app/report/report-cash-assign",
                class: "d-flex",
                permission: Permissions.MANAGE_CASH_REPORTS,
            },
            {
                title: "mileage.report",
                name: "mileage.report",
                fontIcon: <FontAwesomeIcon icon={faGauge} />,
                to: "/app/report/report-mileage",
                class: "d-flex",
                permission: Permissions.MANAGE_MILEAGE_REPORTS,
            },

        ],
    },



    {
        title: "Language Settings",
        name: "Language Settings",
        fontIcon: <FontAwesomeIcon icon={faLanguage} />,
        to: "/app/languages",
        class: "d-flex",
        permission: Permissions.MANAGE_LANGUAGE_CONTENT || Permissions.MANAGE_LANGUAGES,
        subPath:{
          languageContenSubPath:"/app/language-contents",
          languageSubPath:"/app/languages"

        },
        subMenu: [
            {
                title: "Language Contents",
                name: "Language Contents",
                fontIcon: <FontAwesomeIcon icon={faArrowLeft} />,
                to: "/app/language-contents",
                class: "d-flex",
                permission: Permissions.MANAGE_LANGUAGE_CONTENT,
            },
            {
                title: "Language List",
                name: "Language List",
                fontIcon: <FontAwesomeIcon icon={faLanguage} />,
                to: "/app/languages",
                class: "d-flex",
                permission: Permissions.MANAGE_LANGUAGES,
                items: [
                    {
                        title: getFormattedMessage("languages.title"),
                        to: "/app/languages",
                    },
                ],
            },
        ],
    },

    {
        title: "currencies.title",
        name: "currencies",
        fontIcon: <FontAwesomeIcon icon={faDollarSign} />,
        to: "/app/currencies",
        class: "d-flex",
        permission: Permissions.MANAGE_CURRENCY,
        items: [
            {
                title: getFormattedMessage("currencies.title"),
                to: "/app/currencies",
            },
        ],
    },

    {
        title: "roles.permissions.title",
        name: "roles",
        fontIcon: <FontAwesomeIcon icon={faShieldHalved} />,
        to: "/app/roles",
        class: "d-flex",
        permission: Permissions.MANAGE_ROLES,
        items: [
            {
                title: getFormattedMessage("roles.title"),
                to: "/app/roles",
            },
        ],
    },

    {
        title: "settings.title",
        name: "Settings",
        fontIcon: <FontAwesomeIcon icon={faGear} />,
        // to: "/app/languages",
        class: "d-flex",
        permission: Permissions.MANAGE_SETTING,
        subPath:{
            settingSubPath:"/app/settings",
            mailSettingSubPath:"/app/mail-settings",
        },
        subMenu: [
            {
                title: "System Settings",
                name: "System Settings",
                fontIcon: <FontAwesomeIcon icon={faGear} />,
                to: "/app/settings",
                class: "d-flex",
                permission: Permissions.MANAGE_SETTING,
            },
            {
                title:"Mail Settings",
                name: "Mail Settings",
                fontIcon: <FontAwesomeIcon icon={faSms} />,
                to: "/app/mail-settings",
                class: "d-flex",
                permission: Permissions.MANAGE_SETTING,
                // items: [
                //     {
                //         title: getFormattedMessage("languages.title"),
                //         to: "/app/languages",
                //     },
                // ],
            },
        ],
    },

    {
        title: "Templates",
        name: "Templates",
        fontIcon: <FontAwesomeIcon icon={faSms} />,
        class: "d-flex",
        permission: Permissions.MANAGE_USER_NOTIFICATION_TEMPLATE || Permissions.MANAGE_ADMIN_NOTIFICATION_TEMPLATE || Permissions.MANAGE_EMAIL_TEMPLATES || Permissions.MANAGE_ADMIN_EMAIL_TEMPLATE,
        subPath:{
           userNotificationSubPath:"/app/user-notification-templates",
           adminNotificationSubPath:"/app/admin-notification-templates",
           emailNotificationSubPath:"/app/email-templates",
           adminEmailNotificationSubPath:"/app/admin-email-templates",
        },
        subMenu: [
            {
                title: "Salesman Notification Templates",
                name: "Salesman Notification Templates",
                fontIcon: <FontAwesomeIcon icon={faSms} />,
                to: "/app/user-notification-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_USER_NOTIFICATION_TEMPLATE,
            },
            {
                title: "Admin Notification Templates",
                name: "Admin Notification Templates",
                fontIcon: <FontAwesomeIcon icon={faSms} />,
                to: "/app/admin-notification-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_ADMIN_NOTIFICATION_TEMPLATE,
            },
            {
                title: "Customer Email Templates",
                name: "Customer Email Templates",
                fontIcon: <FontAwesomeIcon icon={faEnvelope} />,
                to: "/app/email-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_EMAIL_TEMPLATES,
            },
            {
                title: "Admin Email Templates",
                name: "admin-email-template",
                fontIcon: <FontAwesomeIcon icon={faEnvelope} />,
                to: "/app/admin-email-templates",
                class: "d-flex",
                permission: Permissions.MANAGE_ADMIN_EMAIL_TEMPLATE,
            },
        ],
    },

];
